sudo: required
services:
    - docker

before_install:
    - docker build -t lucasdefariasbezerra/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lucasdefariasbezerra/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: docker
    env: "Docker-env"
    bucket_name: "bucket_name"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: AWS_SECRET_KEY


language: generic