sudo: required
services:
    - docker

before_install:
    - docker build -t lucasdefariasbezerra/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lucasdefariasbezerra/docker-react npm run test

language: generic